### ISSUE TITLE
DOnation Page

### ISSUE THREAD

**Issue by magdaohc** [ohministries/ohministries.github.io#81]
Can you help me formatting what I added in the Donation page?  I feel so ignorant but I am committed to learn :)

**Comment by narthur** [comment]
Is @ErinOHMin able to help you? It might be easier for her since she can show you on your computer.

**Comment by magdaohc** [comment]
Hello Nathan,

She is not here.  He left yesterday.  If you can helpmeet it will be great!
Magda

Magda Rodriguez
President, Ouachita Hills College

46 Madison Way
Amity, AR 71921
Work: 870.342.6210 Ext. 223
Cell: 870.403.3933
www.ohc.org
